name: 🌈 Unit Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  unit-test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: lint fix
        run: pnpm run lint:fix

      - name: Set Timezone
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo "Asia/Shanghai" | sudo tee /etc/timezone
          date
        shell: bash

      - name: unit test
        run: pnpm run test
